### ISSUE TITLE
Business logics in view model and view controller?

### ISSUE THREAD

**Issue by jasonnam** [huynvuit/Survey#4]
Network requests are made on both view model and view controller. Would you share me some insight went there?

**Comment by huynvuit** [comment]
Ah, this is my mistake. When I wrote this view model, I focused on unit test. So I made it clearly for the testing purpose.
I added the flow get access token to reduce a request at the first time. Without this flow, the application still can work normally. Anyway, I forgot to move this flow to the view model :D

**Comment by huynvuit** [comment]
I changed this flow to make everything clear. I updated it to develop branch. But I cannot verify it right now (don't have mac PC at that time). So I will merge it to master branch later.
